// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbenooqqlmhnjerfvkni.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiZW5vb3FxbG1obmplcmZ2a25pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNDEwMDcsImV4cCI6MjA3MDkxNzAwN30.Vyq5Igaw2XlOwIJ5ALwtso03UiOlw-LUSbfHD38ZD0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});